# PTA1012
## 考点
+ 排序


## 问题重述
<details><summary>图片详情</summary><img src="https://raw.githubusercontent.com/ednow/cloudimg/main/githubio/20210714140648.png" alt="找不到图片(Image not found)" onerror="this.onerror=null;this.src='https://gitee.com/ednow/cloudimg/raw/main/githubio/20210714140648.png';" /></details>

## python
### 第一次提交
+ 经研究发现是输出的时候超时了，在23行排序完没有超时(assert False)检查法

<details><summary>图片详情</summary><img src="https://raw.githubusercontent.com/ednow/cloudimg/main/githubio/20210714153942.png" alt="找不到图片(Image not found)" onerror="this.onerror=null;this.src='https://gitee.com/ednow/cloudimg/raw/main/githubio/20210714153942.png';" /></details>

### 第二次提交
+ 测试点2是分数相同的情况下，排名要相同,[参考文献](https://blog.csdn.net/weixin_43725617/article/details/106353957)

<details><summary>图片详情</summary><img src="https://raw.githubusercontent.com/ednow/cloudimg/main/githubio/20210714154429.png" alt="找不到图片(Image not found)" onerror="this.onerror=null;this.src='https://gitee.com/ednow/cloudimg/raw/main/githubio/20210714154429.png';" /></details>

### 第三次提交
+ 感觉修复了第二次提交的bug？（但这种写法大数据下效率更高了？

<details><summary>图片详情</summary><img src="https://raw.githubusercontent.com/ednow/cloudimg/main/githubio/20210714171914.png" alt="找不到图片(Image not found)" onerror="this.onerror=null;this.src='https://gitee.com/ednow/cloudimg/raw/main/githubio/20210714171914.png';" /></details>

### 测试数据藐视
前三个测试数据都是只有5个studentsNum

测试点2：studentsNum：5，checkNum：4

## cpp


### 第一次提交
